spring:
  application:
    name: ledger-service
  jackson:
    time-zone: ${TZ:UTC}
  profiles:
    default: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DATABASE:payment_platform}
    username: ${POSTGRES_USER:payment}
    password: ${POSTGRES_PASSWORD:payment}
  flyway:
    default-schema: ledger
    schemas: ledger
    create-schemas: true
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC
server:
  port: ${SERVER_PORT:8082}
  shutdown: graceful
management:
  endpoints.web.exposure.include: health,info,prometheus
logging:
  pattern:
    console: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX,UTC} level=%-5level service=${spring.application.name} trace=%X{traceId:-} request=%X{requestId:-} logger=%logger{36} - %msg%n"
